sudo: false
language: node_js
node_js:
  - '10'
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email:
    on_success: never
    on_failure: always
install:
  - yarn
script:
  - yarn test:ci
deploy:
  provider: script
  script: bash ./bin/publish.sh
  skip_cleanup: true
  on:
    branch: master
